#!/usr/bin/env node

/**
 * Generate Secrets Script
 * 
 * Run this script to generate secure values for your .env file
 * 
 * Usage:
 *   node generate-secrets.js                    # Interactive mode
 *   node generate-secrets.js mypassword         # Generate with specific password
 *   node generate-secrets.js --write            # Generate and write to .env
 *   node generate-secrets.js --write mypassword # Generate with password and write to .env
 *   node generate-secrets.js --help              # Show help
 */

const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const ENV_FILE = path.join(process.cwd(), '.env');
const ENV_EXAMPLE_FILE = path.join(process.cwd(), '.env.example');

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m'
};

function log(color, message) {
  console.log(colors[color] + message + colors.reset);
}

function showHelp() {
  console.log(`
${colors.bright}🔐 GENERATE SECRETS SCRIPT${colors.reset}

${colors.bright}Usage:${colors.reset}
  node generate-secrets.js [options] [password]

${colors.bright}Options:${colors.reset}
  --write       Write generated values directly to .env file
  --force       Force overwrite existing values in .env
  --example     Create .env.example file with template
  --help        Show this help message

${colors.bright}Examples:${colors.reset}
  node generate-secrets.js
  node generate-secrets.js mypassword
  node generate-secrets.js --write
  node generate-secrets.js --write mypassword
  node generate-secrets.js --force --write
  node generate-secrets.js --example

${colors.bright}Output:${colors.reset}
  - SESSION_SECRET: Random 32-byte hex string
  - METRICS_API_KEY: Random 32-byte hex string  
  - ADMIN_PASSWORD_HASH: Bcrypt hash of password
  `);
  process.exit(0);
}

function generateSessionSecret() {
  return crypto.randomBytes(32).toString('hex');
}

function generateMetricsKey() {
  return crypto.randomBytes(32).toString('hex');
}

function generatePasswordHash(password) {
  return bcrypt.hashSync(password, 10);
}

function readEnvFile() {
  if (!fs.existsSync(ENV_FILE)) {
    return {};
  }
  
  const content = fs.readFileSync(ENV_FILE, 'utf8');
  const env = {};
  
  content.split('\n').forEach(line => {
    // Skip comments and empty lines
    if (line.startsWith('#') || !line.trim()) return;
    
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();
      // Remove quotes if present
      value = value.replace(/^["']|["']$/g, '');
      env[key] = value;
    }
  });
  
  return env;
}

function writeEnvFile(env, force = false) {
  let content = '# Generated by generate-secrets.js\n';
  content += `# Created: ${new Date().toISOString()}\n`;
  content += `# Run 'node generate-secrets.js --help' for more info\n\n`;
  
  // Write in organized sections
  content += '# ─── REQUIRED SECURITY VARIABLES ──────────────────────────────\n';
  const requiredOrder = ['SESSION_SECRET', 'METRICS_API_KEY', 'ADMIN_PASSWORD_HASH'];
  requiredOrder.forEach(key => {
    if (env[key]) {
      content += `${key}=${env[key]}\n`;
    }
  });
  
  content += '\n# ─── SERVER CONFIGURATION ────────────────────────────────────\n';
  const serverOrder = ['PORT', 'NODE_ENV', 'HOST'];
  serverOrder.forEach(key => {
    if (env[key]) {
      content += `${key}=${env[key]}\n`;
    }
  });
  
  content += '\n# ─── LINK CONFIGURATION ──────────────────────────────────────\n';
  const linkOrder = ['TARGET_URL', 'LINK_TTL', 'BOT_URLS'];
  linkOrder.forEach(key => {
    if (env[key]) {
      content += `${key}=${env[key]}\n`;
    }
  });
  
  content += '\n# ─── EXTERNAL SERVICES ───────────────────────────────────────\n';
  const externalOrder = ['IPINFO_TOKEN', 'GA_TRACKING_ID', 'SENTRY_DSN'];
  externalOrder.forEach(key => {
    if (env[key]) {
      content += `${key}=${env[key]}\n`;
    }
  });
  
  content += '\n# ─── LOGGING ─────────────────────────────────────────────────\n';
  const logOrder = ['LOG_LEVEL', 'DEBUG'];
  logOrder.forEach(key => {
    if (env[key]) {
      content += `${key}=${env[key]}\n`;
    }
  });
  
  // Add any remaining variables
  const allKeys = Object.keys(env);
  const usedKeys = [...requiredOrder, ...serverOrder, ...linkOrder, ...externalOrder, ...logOrder];
  const extraKeys = allKeys.filter(key => !usedKeys.includes(key));
  
  if (extraKeys.length > 0) {
    content += '\n# ─── ADDITIONAL VARIABLES ───────────────────────────────────\n';
    extraKeys.forEach(key => {
      content += `${key}=${env[key]}\n`;
    });
  }
  
  // Check if file exists and handle force flag
  if (fs.existsSync(ENV_FILE) && !force) {
    log('yellow', '⚠️  .env file already exists. Use --force to overwrite.');
    const backup = ENV_FILE + '.backup';
    fs.copyFileSync(ENV_FILE, backup);
    log('green', `✅ Backup created at ${backup}`);
  }
  
  fs.writeFileSync(ENV_FILE, content);
  log('green', `✅ Secrets written to ${ENV_FILE}`);
}

function createEnvExample() {
  const example = `# ============================================================================
# REDIRECTOR PRO - EXAMPLE ENVIRONMENT CONFIGURATION
# ============================================================================

# ─── REQUIRED SECURITY VARIABLES (Generate with: node generate-secrets.js) ─
SESSION_SECRET=your-session-secret-here
METRICS_API_KEY=your-metrics-api-key-here
ADMIN_PASSWORD_HASH=your-bcrypt-hash-here

# ─── SERVER CONFIGURATION ─────────────────────────────────────────────────
PORT=10000
NODE_ENV=production
HOST=0.0.0.0

# ─── LINK CONFIGURATION ───────────────────────────────────────────────────
TARGET_URL=https://example.com
LINK_TTL=30m
BOT_URLS=https://www.microsoft.com,https://www.apple.com,https://www.google.com

# ─── EXTERNAL SERVICES ────────────────────────────────────────────────────
IPINFO_TOKEN=your-ipinfo-token-here
GA_TRACKING_ID=UA-XXXXXXXXX-X
SENTRY_DSN=

# ─── LOGGING ──────────────────────────────────────────────────────────────
LOG_LEVEL=info
DEBUG=false

# ─── GENERATE SECURE VALUES ───────────────────────────────────────────────
# Run: node generate-secrets.js --write
# This will generate secure values for all required variables
`;

  fs.writeFileSync(ENV_EXAMPLE_FILE, example);
  log('green', `✅ Created ${ENV_EXAMPLE_FILE}`);
}

async function promptForPassword() {
  return new Promise((resolve) => {
    rl.question(colors.yellow + '🔐 Enter admin password (min 8 chars): ' + colors.reset, (password) => {
      if (password.length < 8) {
        log('red', '❌ Password must be at least 8 characters');
        resolve(promptForPassword());
      } else {
        rl.question(colors.yellow + '🔐 Confirm password: ' + colors.reset, (confirm) => {
          if (password === confirm) {
            resolve(password);
          } else {
            log('red', '❌ Passwords do not match');
            resolve(promptForPassword());
          }
        });
      }
    });
  });
}

async function promptForVar(varName, defaultValue = '') {
  return new Promise((resolve) => {
    const prompt = defaultValue 
      ? `${varName} [${defaultValue}]: `
      : `${varName}: `;
    
    rl.question(colors.cyan + prompt + colors.reset, (value) => {
      resolve(value || defaultValue);
    });
  });
}

async function main() {
  const args = process.argv.slice(2);
  
  // Check for help flag
  if (args.includes('--help')) {
    showHelp();
  }
  
  // Check for example flag
  if (args.includes('--example')) {
    createEnvExample();
    process.exit(0);
  }
  
  const writeToFile = args.includes('--write');
  const forceOverwrite = args.includes('--force');
  
  // Get password from command line or prompt
  let password = args.find(arg => !arg.startsWith('--'));
  
  console.log('\n' + '='.repeat(60));
  log('bright', '🔐 REDIRECTOR PRO - SECURE SECRETS GENERATOR');
  console.log('='.repeat(60) + '\n');

  // Generate secrets
  log('cyan', '📡 Generating secure values...\n');
  
  const sessionSecret = generateSessionSecret();
  const metricsKey = generateMetricsKey();
  
  // Get password
  if (!password) {
    password = await promptForPassword();
  }
  
  const passwordHash = generatePasswordHash(password);
  
  // Display generated values
  log('green', '✅ Generated successfully!\n');
  
  console.log(colors.bright + 'SESSION_SECRET=' + colors.reset + sessionSecret);
  console.log(colors.bright + 'METRICS_API_KEY=' + colors.reset + metricsKey);
  console.log(colors.bright + 'ADMIN_PASSWORD_HASH=' + colors.reset + passwordHash);
  console.log(colors.dim + '(Password: ' + password + ')' + colors.reset);
  
  console.log('\n' + '='.repeat(60));
  
  // Ask about other common variables
  if (!writeToFile) {
    const answer = await promptForVar('Would you like to configure additional variables?', 'no');
    if (answer.toLowerCase().startsWith('y')) {
      const env = {};
      
      env.PORT = await promptForVar('PORT', '10000');
      env.NODE_ENV = await promptForVar('NODE_ENV', 'production');
      env.TARGET_URL = await promptForVar('TARGET_URL', 'https://example.com');
      env.LINK_TTL = await promptForVar('LINK_TTL', '30m');
      env.BOT_URLS = await promptForVar('BOT_URLS', 'https://www.google.com,https://www.microsoft.com');
      env.IPINFO_TOKEN = await promptForVar('IPINFO_TOKEN', '');
      env.LOG_LEVEL = await promptForVar('LOG_LEVEL', 'info');
      env.DEBUG = await promptForVar('DEBUG', 'false');
      
      // Add generated secrets
      env.SESSION_SECRET = sessionSecret;
      env.METRICS_API_KEY = metricsKey;
      env.ADMIN_PASSWORD_HASH = passwordHash;
      
      const writeAnswer = await promptForVar('Write these values to .env file?', 'yes');
      if (writeAnswer.toLowerCase().startsWith('y')) {
        writeEnvFile(env, forceOverwrite);
      }
    } else {
      log('yellow', '\n📋 Copy the values above to your .env file');
    }
  } else {
    // Write to file with generated secrets
    const env = readEnvFile();
    
    // Update with new secrets
    env.SESSION_SECRET = sessionSecret;
    env.METRICS_API_KEY = metricsKey;
    env.ADMIN_PASSWORD_HASH = passwordHash;
    
    // Set defaults for common vars if not present
    if (!env.PORT) env.PORT = '10000';
    if (!env.NODE_ENV) env.NODE_ENV = 'production';
    if (!env.TARGET_URL) env.TARGET_URL = 'https://example.com';
    if (!env.LINK_TTL) env.LINK_TTL = '30m';
    if (!env.BOT_URLS) env.BOT_URLS = 'https://www.google.com,https://www.microsoft.com';
    if (!env.LOG_LEVEL) env.LOG_LEVEL = 'info';
    if (!env.DEBUG) env.DEBUG = 'false';
    
    writeEnvFile(env, forceOverwrite);
  }
  
  // Security warnings
  console.log('\n' + '='.repeat(60));
  log('yellow', '⚠️  IMPORTANT SECURITY NOTES:');
  console.log('   • Store these values securely');
  console.log('   • Never commit .env to version control');
  console.log('   • Change default passwords immediately');
  console.log('   • Use different passwords in production');
  console.log('='.repeat(60) + '\n');
  
  log('green', '✨ Done! Your secure values are ready.\n');
  
  rl.close();
}

// Run the script
main().catch(err => {
  log('red', `\n❌ Error: ${err.message}`);
  process.exit(1);
});
